RESULT=result.ttl

echo "# Generated by BeginkaartParser 2020-09-23" > $RESULT
echo "@prefix sdo: <https://schema.org/> ." >> $RESULT
echo "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> ." >> $RESULT
echo "@prefix trefwoord: <http://documentatie.org/id/trefwoord/> ." >> $RESULT
echo "@prefix def: <http://documentatie.org/def/> ." >> $RESULT
echo "@prefix page: <http://documentatie.org/id/pagina/> ." >> $RESULT
echo "@prefix foaf: <http://xmlns.com/foaf/0.1/> ." >> $RESULT
echo >> $RESULT


# f="../Beginkaarten/Beginkaarten2/Utrecht - Domplein 18 - gesloopt 1938.htm"
for f in ../Beginkaarten/Beginkaarten2/*.htm
do
  echo "Processing $f file..."
  ./BeginkaartParser.py --html "$f" >> $RESULT
  # ttl $RESULT
done

echo $RESULT